"""Trying Hero_Looks again


Revision ID: 16b353caa7c0
Revises: d3e6e8c09b72
Create Date: 2019-06-22 03:36:23.946380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16b353caa7c0'
down_revision = 'd3e6e8c09b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero__looks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('eyes', sa.String(length=100), nullable=True),
    sa.Column('hair', sa.String(length=100), nullable=True),
    sa.Column('clothing', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(length=100), nullable=True),
    sa.Column('skin', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('hero', 'hero_looks_hair')
    op.drop_column('hero', 'hero_looks_symbol')
    op.drop_column('hero', 'hero_looks_body')
    op.drop_column('hero', 'hero_looks_skin')
    op.drop_column('hero', 'hero_looks_eyes')
    op.drop_column('hero', 'hero_looks_clothing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('hero_looks_clothing', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('hero', sa.Column('hero_looks_eyes', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('hero', sa.Column('hero_looks_skin', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('hero', sa.Column('hero_looks_body', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('hero', sa.Column('hero_looks_symbol', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('hero', sa.Column('hero_looks_hair', mysql.VARCHAR(length=100), nullable=True))
    op.drop_table('hero__looks')
    # ### end Alembic commands ###
