"""Hero table

Revision ID: 26afba651c15
Revises: be7d59937c8e
Create Date: 2019-06-17 21:54:17.916652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26afba651c15'
down_revision = 'be7d59937c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=4096), nullable=True),
    sa.Column('hero_class', sa.String(length=4096), nullable=True),
    sa.Column('race', sa.String(length=4096), nullable=True),
    sa.Column('alignment', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero')
    # ### end Alembic commands ###
