"""Added hp column to Hero_Stats

Revision ID: 394b8ecae90b
Revises: c781641c5169
Create Date: 2019-07-08 16:26:06.197908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394b8ecae90b'
down_revision = 'c781641c5169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero__stats', sa.Column('hp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero__stats', 'hp')
    # ### end Alembic commands ###
