"""Added LKUPRace

Revision ID: 558ba8e24d20
Revises: 16b353caa7c0
Create Date: 2019-07-01 17:07:11.735571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558ba8e24d20'
down_revision = '16b353caa7c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lkup_race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('race_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lkup_race')
    # ### end Alembic commands ###
