"""Added Basic, Special, and Class Moves.

Revision ID: 5dd7a4f84ba1
Revises: 0472a421e095
Create Date: 2019-07-11 18:08:01.894672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd7a4f84ba1'
down_revision = '0472a421e095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('move_name', sa.String(length=4096), nullable=True),
    sa.Column('move_description', sa.String(length=4096), nullable=True),
    sa.Column('move_details', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lkup_race_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=4096), nullable=True),
    sa.Column('move_name', sa.String(length=4096), nullable=True),
    sa.Column('move_description', sa.String(length=4096), nullable=True),
    sa.Column('move_details', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('move_name', sa.String(length=4096), nullable=True),
    sa.Column('move_description', sa.String(length=4096), nullable=True),
    sa.Column('move_details', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('special_moves')
    op.drop_table('lkup_race_moves')
    op.drop_table('basic_moves')
    # ### end Alembic commands ###
