"""Restarting

Revision ID: c2cdbf3ec973
Revises: 
Create Date: 2019-06-19 05:39:04.774802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2cdbf3ec973'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=4096), nullable=True),
    sa.Column('content', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lkup_alignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=4096), nullable=True),
    sa.Column('alignment_name', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lkup_looks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=4096), nullable=True),
    sa.Column('look_type', sa.String(length=4096), nullable=True),
    sa.Column('look_details', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('hero_name', sa.String(length=4096), nullable=True),
    sa.Column('hero_class', sa.String(length=4096), nullable=True),
    sa.Column('hero_race', sa.String(length=4096), nullable=True),
    sa.Column('hero_alignment', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero__looks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('eyes', sa.String(length=100), nullable=True),
    sa.Column('hair', sa.String(length=100), nullable=True),
    sa.Column('clothing', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(length=100), nullable=True),
    sa.Column('skin', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero__looks')
    op.drop_table('hero')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('lkup_looks')
    op.drop_table('lkup_alignment')
    op.drop_table('comments')
    # ### end Alembic commands ###
