"""Removed Hero_Looks table- not worth having seperate from Hero.

Revision ID: d3e6e8c09b72
Revises: c2cdbf3ec973
Create Date: 2019-06-22 00:12:27.771424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3e6e8c09b72'
down_revision = 'c2cdbf3ec973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero__looks')
    op.add_column('hero', sa.Column('hero_looks_body', sa.String(length=100), nullable=True))
    op.add_column('hero', sa.Column('hero_looks_clothing', sa.String(length=100), nullable=True))
    op.add_column('hero', sa.Column('hero_looks_eyes', sa.String(length=100), nullable=True))
    op.add_column('hero', sa.Column('hero_looks_hair', sa.String(length=100), nullable=True))
    op.add_column('hero', sa.Column('hero_looks_skin', sa.String(length=100), nullable=True))
    op.add_column('hero', sa.Column('hero_looks_symbol', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero', 'hero_looks_symbol')
    op.drop_column('hero', 'hero_looks_skin')
    op.drop_column('hero', 'hero_looks_hair')
    op.drop_column('hero', 'hero_looks_eyes')
    op.drop_column('hero', 'hero_looks_clothing')
    op.drop_column('hero', 'hero_looks_body')
    op.create_table('hero__looks',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('hero_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('eyes', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('hair', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('clothing', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('body', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('skin', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('symbol', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], name='hero__looks_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
