"""Hero table adjusted- avoiding keywords.

Revision ID: ffe8bfa850f1
Revises: 26afba651c15
Create Date: 2019-06-18 04:42:00.487636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffe8bfa850f1'
down_revision = '26afba651c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('hero_alignment', sa.String(length=4096), nullable=True))
    op.add_column('hero', sa.Column('hero_name', sa.String(length=4096), nullable=True))
    op.add_column('hero', sa.Column('hero_race', sa.String(length=4096), nullable=True))
    op.drop_column('hero', 'race')
    op.drop_column('hero', 'name')
    op.drop_column('hero', 'alignment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('alignment', mysql.VARCHAR(length=4096), nullable=True))
    op.add_column('hero', sa.Column('name', mysql.VARCHAR(length=4096), nullable=True))
    op.add_column('hero', sa.Column('race', mysql.VARCHAR(length=4096), nullable=True))
    op.drop_column('hero', 'hero_race')
    op.drop_column('hero', 'hero_name')
    op.drop_column('hero', 'hero_alignment')
    # ### end Alembic commands ###
